import { renderToStaticMarkup } from 'react-dom/server';
import { MigrationAnalysis } from '../../core/types';
import { ResolvedNames } from '../../core/identity/identity';
import { AnalysisResults } from '../components/AnalysisResults';
import { Header } from '../components/Header';

// The report's only behavior beyond native <details>: strategy tabs switch their panels and
// chart bars (matched by data-row/data-idx) and refresh the totals; the header button flips the theme.
const REPORT_SCRIPT = `(() => {
  const setText = (id, text) => { const el = document.getElementById(id); if (el) el.textContent = text; };
  const refreshTotals = () => {
    const bars = [...document.querySelectorAll('[data-coverage]:not([hidden])')];
    const sum = (name) => bars.reduce((total, bar) => total + Number(bar.getAttribute(name)), 0);
    setText('stat-average', Math.round(sum('data-coverage') / (bars.length || 1)) + '%');
    setText('stat-missing', String(sum('data-missing')));
    setText('stat-excess', String(sum('data-excess')));
  };
  document.addEventListener('click', (event) => {
    const target = event.target.closest?.('[data-tab-row], [data-theme-toggle]');
    if (!target) return;
    if (target.hasAttribute('data-theme-toggle')) {
      document.documentElement.classList.toggle('dark');
      return;
    }
    const row = target.getAttribute('data-tab-row');
    const idx = target.getAttribute('data-idx');
    document.querySelectorAll('[data-row="' + row + '"]').forEach((el) => el.toggleAttribute('hidden', el.getAttribute('data-idx') !== idx));
    document.querySelectorAll('[data-tab-row="' + row + '"]').forEach((tab) => tab.setAttribute('aria-pressed', String(tab === target)));
    refreshTotals();
  });
})();`;

const escapeHtml = (value: string): string => value.replace(/[&<>"']/g, (c) => `&#${c.charCodeAt(0)};`);

interface ReportOptions {
  theme: 'light' | 'dark';
  vaultName: string;
  subscriptionId: string;
  /** The app's compiled CSS, inlined so the file is self-contained. */
  css: string;
  generatedAt?: Date;
}

/**
 * A single self-contained HTML file rendering the same components as the live
 * analysis view, for sharing with colleagues who don't run the tool.
 */
export const exportToHtml = (
  results: MigrationAnalysis[],
  selectedRoles: Record<string, number>,
  resolvedNames: ResolvedNames,
  { theme, vaultName, subscriptionId, css, generatedAt = new Date() }: ReportOptions
): string => {
  const meta = 'text-neutral-900 dark:text-neutral-100 font-semibold break-all';
  const body = renderToStaticMarkup(
    <>
      <Header user={null} />
      <main className="max-w-[1600px] mx-auto p-3 sm:p-4 lg:p-6">
        <div className="bg-white dark:bg-neutral-800 rounded border border-neutral-200 dark:border-neutral-700 shadow-sm">
          <div className="px-4 py-4 sm:px-6 border-b border-neutral-200 dark:border-neutral-700 bg-neutral-50 dark:bg-neutral-800/50 flex flex-col gap-2 sm:flex-row sm:flex-wrap sm:items-center sm:justify-between">
            <h2 className="min-w-0 break-words text-lg font-semibold">Analysis: {vaultName}</h2>
            <div className="flex flex-col gap-1 text-xs text-neutral-600 dark:text-neutral-400 sm:flex-row sm:gap-4">
              <span>Subscription: <b className={meta}>{subscriptionId || 'N/A'}</b></span>
              <span>Identities: <b className={meta}>{results.length}</b></span>
              <span>Generated: <b className={meta}>{generatedAt.toLocaleString()}</b></span>
            </div>
          </div>
          <div className="p-4 sm:p-6">
            {results.length === 0 ? (
              <p className="text-sm text-neutral-600 dark:text-neutral-400">No identities selected for export.</p>
            ) : (
              <AnalysisResults results={results} selectedRoles={selectedRoles} resolvedNames={resolvedNames} />
            )}
          </div>
        </div>
        <footer className="py-4 text-center text-[11px] text-neutral-500">
          Generated by Azure Key Vault RBAC Migrator · {generatedAt.toISOString()}
        </footer>
      </main>
    </>
  );

  return `<!DOCTYPE html>
<html lang="en" class="${theme === 'dark' ? 'dark' : ''}">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Key Vault RBAC Analysis - ${escapeHtml(vaultName)}</title>
<style>${css.replace(/<\/style/gi, '<\\/style')}</style>
</head>
<body class="bg-neutral-100 dark:bg-neutral-900 font-sans text-neutral-900 dark:text-neutral-100 antialiased">
${body}
<script>${REPORT_SCRIPT}</script>
</body>
</html>`;
};
